### ISSUE TITLE
it must be user error: navigation and organize imports

### ISSUE THREAD

**Issue by paulp** [mads-hartmann/ensime.tmbundle#7] opened 2010-12-14 20:13 UTC
I can't get much to work.  The first two things I tried were:

"Navigation". Â Result:  /Users/paulp/Library/Application Support/TextMate/Bundles/ensime.tmbundle/Support/ensime.rb:155:in `navigate': undefined method`collect' for nil:NilClass (NoMethodError) from /tmp/temp_textmate.2SmPeG:5

"Organize Imports".  Result: It churns for a while, then never removes anything, even imports I add just for the purpose of not being used.

I'm using the 2.8.1 final bundle for ensime and the heads of the scala.tmbundle and ensime.tmbundle repositories.  It's connected and they're talking -- the type inspector works, for instance -- so it's not a "is the power on" failure.

**Comment by mads-hartmann** [comment] 2010-12-14 20:47
Hey Paul, 
Would you be able to share the project / .ensime file?

**Comment by mads-hartmann** [comment] 2010-12-14 20:57
If you aren't allowed to share the code you can try out my project here

https://github.com/mads379/Functional-Dictionary/tree/Screencast_1

Switch branch to Screencast_1 and everything should be running smoothly.

**Comment by paulp** [comment] 2010-12-14 21:01
The project I tried it out on was this:

  https://github.com/mads379/ensime.tmbundle/issues#issue/7/comment/611717

The only thing the version on github lacks is the .ensime file, which is this:

(:project-package "improving"
 :use-sbt t
 :root-dir "/repo/scala-improving")

**Comment by paulp** [comment] 2010-12-14 21:01
Aaagh, paste/texto fail.  The project is this: https://github.com/paulp/scala-improving

**Comment by mads-hartmann** [comment] 2010-12-14 21:24
Looking at the logs I see the following error 

<pre>scala.tools.nsc.MissingRequirementError: class scala.runtime.BooleanRef not found.</pre>


It also happens in Emacs so it seems to be a problem with Ensime. Aemon is probably better suited to help you at this point. 

Trying to compile the project with sbt gives me the error 

<pre>[error] /Users/Mads/dev/projects/scala-improving/src/main/scala/Profiler.scala:11: value yourkit is not a member of package com
[error]   import _root_.com.yourkit.api._
[error]                     ^
[error] one error found</pre> 


But I don't think it has anything to do with the Ensime problem ;)

**Comment by paulp** [comment] 2010-12-14 21:32
Sorry, I left out a change I had to make (and I believe this is a bug somewhere as well.) My project/build.properties used to say:

build.scala.versions=2.8.1 2.9.0-SNAPSHOT

And I had to change this to only list 2.8.1, or I got the MissingRequirementError you did.

You're right, the dependency on yourkit is pretty unrelated.  Thanks for alerting me; it's too easy with sbt to forget you have dependencies on custom things.

**Comment by mads-hartmann** [comment] 2010-12-14 21:40
Sweet, I was able to reproduce the error with the change in the scala version. 

I'm sorry but I don't have time to fix it straight way - I'm in the midst of writing a business case (I know, it's horrible) that I have to hand-in in 14 hours and knowing myself it would be dangerous to start tinkering with my buggy ruby code at this point ;)

Should be able to fix it tomorrow or tonight when I've printed this heap of ***\* I'm currently writing. 

Mads

**Comment by mads-hartmann** [comment] 2010-12-14 23:11
omg. I had hard-coded the package name in the swank message. Navigation should work in the master branch now.

Please don't tell on me ;) Will investigate the organize imports bug you mentioned next

**Comment by mads-hartmann** [comment] 2010-12-14 23:47
It seems that the organize imports is also broken in ensime. Would you mind opening a ticket in the ensime project?

**Comment by paulp** [comment] 2010-12-15 05:04
OK, it's ticketed.  https://github.com/aemoncannon/ensime/issues/issue/113

**Comment by mads-hartmann** [comment] 2010-12-15 12:28
Great, I'll close this one for now. Thanks for trying out the bundle :)

**Closed as completed by mads-hartmann** 2010-12-15 12:28 UTC
